name: Test

on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "Makefile"
      - ".github/workflows/test.yaml"
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "Makefile"
      - ".github/workflows/test.yaml"


env:
  GO_VERSION: 1.19

jobs:
  test:
    name: Unit Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Setup Go Environment
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Go Get dependencies
        run: go get -v -t -d ./...
      - name: Go Test
        # ref https://github.com/megaease/easeprobe/blob/main/.github/workflows/test.yaml
        # run: make test TEST_FLAGS="-coverprofile=coverage.txt -covermode=atomic"
        # makefile: go test -gcflags=-l -cover -race ${TEST_FLAGS} -v ./...
        run: go test -gcflags=-l -cover -race -coverprofile=coverage.txt -covermode=atomic -v ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          file: ./coverage.txt
